language: python
env:
    - FLIT=true
    - FLIT=false

python:
    - 3.5
    - "nightly"
before_install:
    - pip install flit nose
install:
    - if [ "$FLIT"=="true" ]; then 
        flit install;
      else
        pip install . ;
      fi
script:
    - nosetests -c setup.cfg
